server:
  port: 9000

logging:
  level:
    root: debug

spring:
  datasource:
    url: jdbc:h2:mem:widgetdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console


management:
  endpoint:
    health:
      show-detail: always
      show-components: always

cors:
  allowed-origins:
    - http://localhost:3000
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
  allowed-headers:
    - Content-Type
    - Authorization
  allow-credentials: true
  max-age: 3600